Building cant be placed on occupied slot
dllarsson/cuddly-palm-tree pull request #25
Opened 2021-04-10 11:18 UTC by relinkz

Fixed collition with ghost building and enemies does not collide with each other

2021-04-10 13:16 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/EnemyDragon.cs
> +        {
Tror vi kan lösa detta utan att snvända Tags. För många tags kan snabbt spåra ur.
Exempelvis kan vi använda en generisk public isEnabled boolean kopplad till objektet (se Tower.cs, vi kan göra isEnabled public så slipper vi en tag)

2021-04-10 13:18 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/EnemyDragon.cs
> +        }
Varför IgnoreCollision? Räcker det inte om vi inverterar if-satsen innan och ta bort en else? Blir väl ingen skillnad?

2021-04-10 13:20 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/EventHandler.cs
> +    private Coroutine buildingPlacementRoutine;
Vad gör dessa?  Variablerna är i fel script?

2021-04-10 13:21 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
>      private void Start()
Kan använsa Color istället för Vector4 så är det tydligare vad som lagras.

2021-04-10 13:22 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
> +    bool canBePlacedOnSpot()
Kodstandard!

2021-04-10 13:28 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
> +        Collider2D[] collidedThings = new Collider2D[1];
Behöver vi ha 2 variabler som bara används 1 gång?

2021-04-10 13:29 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
> +        if (nrOfCollitions != 0)
Kodstandard naming: Undvik förkortningar, måste man ha det så är förkortningen i stora bokstäver.

2021-04-10 13:32 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
> +                createdAsset.tag = "Tower";
Som sagt, vi borde försöka undvika att ändra tags gametime. Detta förstör modulariteten. Använd istället generiska vooleans (isEnabled == true) från objektet som spawnas

2021-04-10 13:34 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
> +        createdAsset.tag = "Ghost";
Se första kommentaren

2021-04-10 13:38 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
> +
Bra lösning med olika färger!

2021-04-10 13:38 UTC, Zexenek requested changes
Se kommentarer

2021-04-10 21:08 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/EnemyDragon.cs
> +        {
Eller ännu bättre, istället för att kolla efter vad som INTE kan skada den, kolla efter vad som KAN skada den..
 (Alltså Tower eller projectile)

2021-04-10 21:15 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/EnemyDragon.cs
> +        }
T.ex `if(tower || projectile)
{
        health -= damage;
}`

2021-04-13 17:33 UTC, relinkz commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
> +        Collider2D[] collidedThings = new Collider2D[1];
lättare att läsa

2021-04-13 17:34 UTC, relinkz commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
> +        Collider2D[] collidedThings = new Collider2D[1];
var

2021-04-24 08:16 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
> +                createdAsset.tag = "Tower";
Ta bort tag

2021-04-24 08:16 UTC, Zexenek commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
> +        createdAsset.tag = "Ghost";
Ta bort tag

2021-04-24 08:55 UTC, relinkz commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
>      private void Start()
done

2021-04-24 08:56 UTC, relinkz commented on CuddleTreeDefenseGame/Assets/Scripts/SpawnHandler.cs
> +    bool canBePlacedOnSpot()
ops, done

2021-04-24 09:03 UTC, relinkz commented on CuddleTreeDefenseGame/Assets/Scripts/EnemyDragon.cs
> +        }
tog diuna ändringar så alla kommentarer i denna fil är ju skit samma xD

2021-04-24 09:04 UTC, relinkz commented on CuddleTreeDefenseGame/Assets/Scripts/EnemyDragon.cs
> +        {
Din kommit har fixxat skiten

2021-04-24 09:12 UTC, merged